prompt Importing table T_SYS_NOTIFICATION_TEMPLATE...
set feedback off
set define off
insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('b684376839df40f9badf0818858b0b86', 'LATAM Applicant Reset Password Mail-Español', '2', 'd35ef0373a6a435f98f6bdb0c70bef05', '20', '1', 1, 'admingu', '11-10月-19 04.19.29.334000 下午', 'admingu', '13-11月-19 02.48.58.460000 下午', 0, '<p>Hola,&nbsp;<span class="str-style"><input value=" Applicant Name " type="button"/>&nbsp;</span>!<br/></p><p><br/></p><p>Gracias por su solicitud.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p><p>Nos complace invitarle a una entrevista en haikonwei, por favor haga clic en el enlace siguiente para completar la información de la entrevista</p><p>Inicio：<span><input value=" Send Date " type="button"/></span></p><p>User:<span><input value=" Login_name " type="button"/></span></p><p>Contrasena：<span><input value=" Login_password " type="button"/></span></p><p>Gracias,&nbsp;</p><p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Hikvision <span><input value=" Business Area " type="button"/></span></p>', 'Hikvision Personal Information Collection Reset Password Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('35ca3d8469ba43d497c29fae6802db3e', 'LATAM Applicant Creat Account Mail', '0', 'd35ef0373a6a435f98f6bdb0c70bef05', '10', '1', 1, 'admingu', '23-10月-19 01.50.10.361000 下午', 'admingu', '13-11月-19 02.49.30.395000 下午', 0, '<p>Hello,<span><input value=" Applicant Name " type="button"/></span><span class="str-style"> </span>!</p><p>&nbsp;</p><p>We would like to invite you to be part of the Hikvision team!</p><p>For this you must accept our offer letter, sign and send all the documentation in the link until tomorrow:</p><p><span><input value=" Registrantion Url" type="button"/></span><span class="str-style"></span></p><p>Start:&nbsp;<span><input value=" Send Date " type="button"/></span></p><p>User:&nbsp;<span><input value=" Login_name " type="button"/></span>&nbsp;Password:<span><input value=" Login_password " type="button"/></span></p><p>&nbsp;</p><p>Thank you,</p>', 'Hikvsion Personal Information Collection Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('cf2b01f58a2b4cec8d3412f0f09dd7c3', 'LATAM  Reset Password Mail', '0', 'd35ef0373a6a435f98f6bdb0c70bef05', '20', '1', 1, 'admingu', '11-10月-19 04.17.23.584000 下午', 'admingu', '13-11月-19 02.48.38.173000 下午', 0, '<p>Dear <span><input value=" Applicant Name " type="button"/></span>：</p><p><br/></p><p>Thank you for your application.</p><p>We are pleased to invite you to participate in the Hikvision interview, please click the following link to fill in the interview information .</p><p>Registrantion:<span><input value=" Send Date " type="button"/></span></p><p>user name：<span><input value=" Login_name " type="button"/></span></p><p>password：<span><input value=" Login_password " type="button"/></span></p><p>Hikvision <span><input value=" Business Area " type="button"/></span></p><p><br/></p>', 'Hikvsion Personal Information Collection reset password Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('720386e7efc7494ea1782ed36bb73c67', 'ASIA Applicant Creat Account Mail', '0', 'b8642f9ecea149d4a8aa77353960709a', '10', '1', 1, 'admingu', '23-10月-19 03.45.43.514000 下午', 'admingu', '15-11月-19 05.47.57.397000 下午', 0, '<p>Hello,<span><input type="button" value=" Applicant Name "/></span>:</p><p><br/></p><p>We would like to invite you to be part of the Hikvision team!</p><p>For this you must accept our offer letter, sign and send all the documentation in the link until tomorrow:</p><p><span><input type="button" value=" Registrantion Url"/></span></p><p><br/></p><p>User name:<span><input type="button" value=" Login_name "/></span>&nbsp;</p><p>Password:<span><input type="button" value=" Login_password "/></span></p><p>Thank you.</p><p style="text-align: right;">Hikvision&nbsp;<span><input type="button" value=" Business Area "/></span></p><p style="text-align: right;"><input type="button" value=" Send Date "/><br/></p>', 'Hikvsion Personal Information Collection Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('12ae2e300b7640a4a9aea4f67b744fbb', 'LATAM Applicant Creat Account Mail-Español', '2', 'd35ef0373a6a435f98f6bdb0c70bef05', '10', '1', 1, 'admingu', '23-10月-19 01.55.48.898000 下午', 'admingu', '13-11月-19 02.49.38.859000 下午', 0, '<p>Hola, <span class="str-style"> <span><input value=" Applicant Name " type="button"/></span> </span>!</p><p><br/></p><p>Nos gustaría invitarle a ser parte del equipo de Hikvision!</p><p>Para esto debe aceptar nuestra carta de oferta, firmar y enviar toda la documentación en el link hasta mañana:</p><p><span class="str-style"><span><input value=" Registrantion Url" type="button"/></span></span></p><p>Inicio:&nbsp;<span><input value=" Send Date " type="button"/></span></p><p>User:&nbsp;<span><input value=" Login_name " type="button"/></span>&nbsp;Contrasena:<span><input value=" Login_password " type="button"/></span></p><p>Gracias,&nbsp;</p>', 'Hikvsion Personal Information Collection Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('9eb6cb5da93941fb9f3fd68a8311d266', 'MENA Applicant Creat Account Mail', '0', '3df154d1afa84fa3b786658772c64938', '10', '1', 1, 'admingu', '23-10月-19 03.42.05.282000 下午', 'admin', '14-11月-19 11.10.50.550000 上午', 0, '<p>Hello, <span><input value=" Applicant Name " type="button"/></span>&nbsp;:</p><p><br/></p><p>We would like to invite you to be part of the Hikvision team!</p><p>For this you must accept our offer letter, sign and send all the documentation in the link until tomorrow:</p><p><span><input value=" Registrantion Url" type="button"/></span></p><p><br/></p><p>User name:&nbsp;<span><input value=" Login_name " type="button"/></span>&nbsp;</p><p>Password:&nbsp;<span><input value=" Login_password " type="button"/></span></p><p>&nbsp;</p><p>Thank you.</p><p style="text-align: right;">Hikvision<span><input value=" Business Area " type="button"/></span></p><p style="text-align: right;">&nbsp;<input value=" Send Date " type="button"/><br/></p>', 'Hikvsion Personal Information Collection Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('824e670189b8443982b1e20d8d4c6ba4', 'LATAM Applicant Creat Account Mail-Português', '1', 'd35ef0373a6a435f98f6bdb0c70bef05', '10', '1', 1, 'admin', '16-10月-19 11.13.49.844000 上午', 'admingu', '08-11月-19 02.06.38.129000 下午', 0, '<p>Olá, <span class="str-style"> <span><input value=" Applicant Name " type="button"/></span></span>!</p><p>&nbsp;</p><p>Gostaríamos de convidá-lo para fazer parte da equipe do Hikvision!</p><p>Para isso você deve aceitar a nossa carta de oferta, assinar e enviar toda a documentação no link até amanhã:</p><p><span><input value=" Registrantion Url" type="button"/></span><span class="str-style"></span></p><p>Início:&nbsp;<span class="str-style"> <span><input value=" Send Date " type="button"/></span> </span></p><p>Usuário:&nbsp;<span class="str-style"> <span class="str-style"> <span><input value=" Login_name " type="button"/></span> </span></span>&nbsp;Senha:<span><input value=" Login_password " type="button"/></span></p><p>Obrigado!</p>', 'Hikvision Personal Information Collection Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('dd5f638ca9b94b3980479bf6d644c3f8', 'ASIA Applicant Reject Mail', '0', 'b8642f9ecea149d4a8aa77353960709a', '30', '1', 1, 'admingu', '11-10月-19 04.14.42.084000 下午', 'admin', '14-11月-19 11.11.19.598000 上午', 0, '<p><span style="background-color: transparent; color: rgb(51, 51, 51);">Dear <span><input value=" Applicant Name " type="button"/></span>：</span></p><p><span style="background-color: transparent; color: rgb(51, 51, 51);"><br/></span></p><p>Your applicaiton has been rejected,Please amend it and send again!</p><p>&nbsp;Thank you.</p><p style="text-align: right;">Hikvison&nbsp;<span><input value=" Business Area " type="button"/></span></p><p style="text-align: right;"><span><input value=" Send Date " type="button"/></span></p>', 'Hikvision Personal Information Collection Reject Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('dc35223789074850a3c02dfeb81b3ba4', 'LATAM Applicant Reject Mail', '0', 'd35ef0373a6a435f98f6bdb0c70bef05', '30', '1', 1, 'admingu', '11-10月-19 04.17.40.108000 下午', 'admingu', '13-11月-19 02.48.42.683000 下午', 0, '<p><span style="background-color: transparent; color: rgb(51, 51, 51);">Dear <span><input value=" Applicant Name " type="button"/></span>：</span></p><p><span style="background-color: transparent; color: rgb(51, 51, 51);"><br/></span></p><p>Your applicaiton has been rejected,Please amend it and send again!</p><p>Hikvision Business Area</p><p><span><input value=" Send Date " type="button"/></span></p>', 'Hikvision Personal Information Collection Reject Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('7a11a07aa6754b6fb0f5be40eee750f2', 'LATAM Applicant  Reject Mail-Português', '1', 'd35ef0373a6a435f98f6bdb0c70bef05', '30', '1', 1, 'admingu', '11-10月-19 04.18.47.135000 下午', 'admin', '04-11月-19 07.39.53.186000 下午', 0, '<p>Olá,<span><input value=" Applicant Name " type="button"/></span>!</p><p><br/></p><p>O SEU pedido FOI rejeitado, por favor, altere-o e envie-o novamente!</p><p><span><input value=" Business Area " type="button"/></span></p><p><span><span><input value=" Send Date " type="button"/></span></span></p><p><br/></p>', 'Hikvsion Personal Information Collection Reject Messengers Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('a11f94c2f604476eb2bd393e1a107241', 'ASIA Applicant Submit Mail', '0', 'b8642f9ecea149d4a8aa77353960709a', '60', '1', 1, 'admingu', '04-11月-19 11.24.30.152000 上午', 'admin', '14-11月-19 11.11.23.498000 上午', 0, '<p><span><input value=" Applicant Name " type="button"/></span> has already submitted his/her personal information collection form. Please pay attention.<br/></p><p style="text-align: right;"><span><input value=" Send Date " type="button"/></span></p><p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p><p>&nbsp;</p>', 'XXXX has already submitted his/her personal information collection form.');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('6ae4296c54eb42029335b2fc57afbc2d', 'LATAM Applicant Reject Mail-Español', '2', 'd35ef0373a6a435f98f6bdb0c70bef05', '30', '1', 1, 'admingu', '11-10月-19 04.19.44.202000 下午', 'admin', '04-11月-19 07.43.51.130000 下午', 0, '<p>Hola,&nbsp;<span class="str-style"><input value=" Applicant Name " type="button"/>&nbsp;</span>!</p><p>&nbsp; &nbsp; &nbsp;&nbsp;</p><p>&nbsp;Su solicitud ha sido rechazada, por favor cambie y envíe de nuevo!¡Su solicitud ha sido rechazada, por favor cambie y envíe de nuevo!</p><p>Hikvision&nbsp;<span><input value=" Business Area " type="button"/></span></p><p><span><input value=" Send Date " type="button"/></span></p>', 'Hikvsion Personal Information Collection Reject Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('1eb2914c8ba143ba8ce3aabea3613abe', 'Employee Reset Password Messengers', '0', 'fc0d1a87003b4788b7315659f56bedec', '40', '1', 1, 'admingu', '11-10月-19 04.22.12.313000 下午', 'admin', '04-11月-19 08.02.41.545000 下午', 0, '<p>Hello!&nbsp;<input value=" Applicant Name " type="button"/></p><p><br/></p><p>&nbsp; &nbsp; &nbsp;Your password is reseted! you can login the system with the followed url:</p><p><span class="str-style" style="display: inline-block; color: rgb(144, 147, 153); height: 26px; font-size: 12px; margin: 0px 10px 0px 0px; padding: 0px 10px; line-height: 24px; border-radius: 4px;"><input value=" Registrantion Url" type="button"/></span></p><p>user name：<input value=" Login_name " type="button"/></p><p>password：<input value=" Login_password " type="button"/></p><p>Hikvision&nbsp;<input value=" Business Area " type="button"/></p>', 'Hikvision Personal Information Collection Reset Password Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('f43ecd776fc948c4aa57cf13c11aecdf', 'MENA Applicant Submit Mail', '0', '3df154d1afa84fa3b786658772c64938', '60', '1', 1, 'admingu', '31-10月-19 04.03.19.407000 下午', 'admingu', '15-11月-19 05.47.20.591000 下午', 0, '<p><span><input type="button" value=" Applicant Name "/></span> has already submitted his/her personal information collection form. Please pay attention.<br/></p><p style="text-align: right;"><span><input type="button" value=" Send Date "/></span></p>', 'XXXX has already submitted his/her personal information collection form.');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('296f034b583c44748fa0af0fe98c1a71', 'LATAM Applicant Submit Mail', '0', 'd35ef0373a6a435f98f6bdb0c70bef05', '60', '1', 1, 'admingu', '31-10月-19 03.59.10.206000 下午', 'admingu', '06-11月-19 03.12.44.741000 下午', 0, '<p><span><input value=" Applicant Name " type="button"/></span> has already submitted his/her personal information collection form. Please pay attention.<br/></p><p>&nbsp; &nbsp; &nbsp;</p><p><br/></p>', 'XXXX has already submitted his/her personal information collection form.');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('c226357086f1401c821720bcde71fc2b', 'MENA  Applicant Reject Mail', '0', '3df154d1afa84fa3b786658772c64938', '30', '1', 1, 'admingu', '11-10月-19 04.16.36.429000 下午', 'admin', '14-11月-19 11.10.57.531000 上午', 0, '<p><span style="background-color: transparent; color: rgb(51, 51, 51);">Dear <span><input value=" Applicant Name " type="button"/></span>：</span></p><p><span style="background-color: transparent; color: rgb(51, 51, 51);"><br/></span></p><p>Your applicaiton has been rejected,Please amend it and send again!</p><p>Thank you.<br/></p><p><br/></p><p style="text-align: right;"><span>Hikvision&nbsp;<span><input value=" Business Area " type="button"/></span></span></p><p style="text-align: right;"><span><input value=" Send Date " type="button"/></span></p>', 'Hikvision Personal Information Collection Reject Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('f9333582747e41188aed7b6f0762ae04', 'LATAM Applicant Reset Password Mail-Português', '1', 'd35ef0373a6a435f98f6bdb0c70bef05', '20', '1', 1, 'admingu', '11-10月-19 04.18.29.681000 下午', 'admingu', '13-11月-19 02.48.50.186000 下午', 0, '<p>Olá,&nbsp;<span class="str-style"><input value=" Applicant Name " type="button"/></span>!</p><p><br/></p><p>Obrigado PELA SUA inscrição.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p><p>&nbsp;Temos o prazer de convidá-lo a participar Na entrevista Hikvision, por favor clique no seguinte link para preencher a informação Da entrevista.</p><p>Início:<span><input value=" Send Date " type="button"/></span></p><p>Usuário：<span><input value=" Login_name " type="button"/></span></p><p>Senha：<span><input value=" Login_password " type="button"/></span></p><p>Obrigado</p><p style="text-align: right;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Hikvision <span><input value=" Business Area " type="button"/></span></p>', 'Hikvision Personal Information Collection Reset Password Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('8c7f3b8a2df44212bd4256129d1ba8b2', 'Employee Reset Password Messengers', '0', 'a8050acc1571473190756ec526b8c9ad', '40', '1', 1, 'admingu', '11-10月-19 04.28.13.478000 下午', 'admin', '04-11月-19 08.05.10.128000 下午', 0, '<p>Hello!&nbsp;<input value=" Applicant Name " type="button"/></p><p><br/></p><p>&nbsp; &nbsp; &nbsp;Your password is reseted! you can login the system with the followed url:</p><p><span class="str-style" style="display: inline-block; color: rgb(144, 147, 153); height: 26px; font-size: 12px; margin: 0px 10px 0px 0px; padding: 0px 10px; line-height: 24px; border-radius: 4px;"><input value=" Registrantion Url" type="button"/></span></p><p>user name：<input value=" Login_name " type="button"/></p><p>password：<input value=" Login_password " type="button"/></p><p>Hikvision&nbsp;<input value=" Business Area " type="button"/></p>', 'Hikvision Personal Information Collection Reset Password Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('06026aa43e37426f8fab43eb573c0b0e', 'Employee Account Messengers', '0', '742755ee8a814709a60b967ac8763420', '50', '1', 1, 'admingu', '04-11月-19 11.16.30.222000 上午', 'admin', '15-11月-19 06.10.49.520000 下午', 0, '<p style="text-align: left;">Hello, <span><input value=" Applicant Name " type="button"/></span> !</p><p style="text-align: left;">&nbsp;</p><p style="text-align: left;">We are glad to inform you that your account is created!</p><p style="text-align: left;">You can login the system with the followed url:</p><p style="text-align: left;"><span class="str-style" style="display: inline-block; color: rgb(144, 147, 153); height: 26px; font-size: 12px; margin: 0px 10px 0px 0px; padding: 0px 10px; line-height: 24px; border-radius: 4px;"><span><input value=" Registrantion Url" type="button"/></span></span></p><p><br/></p><p style="text-align: left;">User name: <span><input value=" Login_name " type="button"/></span>&nbsp;</p><p style="text-align: left;">Password:<span><input value=" Login_password " type="button"/></span></p><p style="text-align: left;">Thank you.</p><p style="text-align: right;"><input value=" Send Date " type="button"/><br/></p>', 'Hikvision Personal Information Collection Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('f6002f192ba6433984f5806e392f6550', 'Employee Account Messengers', '0', 'a8050acc1571473190756ec526b8c9ad', '50', '1', 1, 'admingu', '04-11月-19 11.18.00.696000 上午', 'admin', '14-11月-19 11.14.56.315000 上午', 0, '<p>Hello,&nbsp;<input value=" Applicant Name " type="button"/>&nbsp;!</p><p>&nbsp;</p><p>We are glad to inform you that your account is created!</p><p>You can login the system with the followed url:</p><p><span class="str-style" style="display: inline-block; color: rgb(144, 147, 153); height: 26px; font-size: 12px; margin: 0px 10px 0px 0px; padding: 0px 10px; line-height: 24px; border-radius: 4px;"><input value=" Registrantion Url" type="button"/></span></p><p>User name:&nbsp;<input value=" Login_name " type="button"/>&nbsp;</p><p>Password:<input value=" Login_password " type="button"/></p><p>Thank you.</p><p><input value=" Send Date " type="button"/><br/></p>', 'Hikvsion Personal Information Collection Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('a1f2f1e18b614689adda4a4595d732c2', 'ASIA Applicant Reset Password Mail', '0', 'b8642f9ecea149d4a8aa77353960709a', '20', '1', 1, 'admingu', '11-10月-19 04.14.16.324000 下午', 'admin', '14-11月-19 11.11.35.538000 上午', 0, '<p>Dear&nbsp;<span><input value=" Applicant Name " type="button"/>:</span></p><p><span><br/></span></p><p>Thank you for your application.</p><p>We are pleased to invite you to participate in the Hikvision interview, please click the following link to fill in the interview information .</p><p><span><input value=" Registrantion Url" type="button"/></span></p><p>User name：<span><input value=" Login_name " type="button"/></span></p><p>Password：<span><input value=" Login_password " type="button"/></span></p><p>Thank you.</p><p style="text-align: right;">Hikvision <span><input value=" Business Area " type="button"/></span></p><p style="text-align: right;"><span><span><input value=" Send Date " type="button"/></span></span></p>', 'Hikvision Personal Information Collection Reset Password Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('fb7e901d81c9436b9d0bdab14ced4289', 'MENA  Applicant Reset Password Mail', '0', '3df154d1afa84fa3b786658772c64938', '20', '1', 1, 'admingu', '11-10月-19 04.16.15.176000 下午', 'admin', '14-11月-19 11.11.05.004000 上午', 0, '<p>Dear&nbsp;&nbsp;<span><input value=" Applicant Name " type="button"/>:</span></p><p><span><br/></span></p><p>Thank you for your application.</p><p>We are pleased to invite you to participate in the Hikvision interview, please click the following link to fill in the interview information .</p><p><span><input value=" Registrantion Url" type="button"/></span></p><p>User name：<span><input value=" Login_name " type="button"/></span></p><p>Password：<span><input value=" Login_password " type="button"/></span></p><p>Thank you.</p><p style="text-align: right;">Hikvision <span><input value=" Business Area " type="button"/></span></p><p style="text-align: right;"><span><span><input value=" Send Date " type="button"/></span></span></p>', 'Hikvision Personal Information Collection Reset Password Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('c98e28a25b864ce7b10da00e93bc22c3', 'Employee Account Messengers', '0', 'fc0d1a87003b4788b7315659f56bedec', '50', '1', 1, 'admingu', '04-11月-19 11.15.13.975000 上午', 'admin', '14-11月-19 11.14.07.136000 上午', 0, '<p style="text-align: left;">Hello,&nbsp;<input value=" Applicant Name " type="button"/>&nbsp;!</p><p style="text-align: left;">&nbsp;</p><p style="text-align: left;">We are glad to inform you that your account is created!</p><p style="text-align: left;">You can login the system with the followed url:</p><p style="text-align: left;"><input value=" Registrantion Url" type="button"/></p><p><br/></p><p style="text-align: left;">User name:&nbsp;<input value=" Login_name " type="button"/>&nbsp;</p><p style="text-align: left;">Password:<input value=" Login_password " type="button"/></p><p style="text-align: left;">Thank you.</p><p style="text-align: right;"><input value=" Send Date " type="button"/><br/></p>', 'Hikvision Personal Information Collection Mail');

insert into T_SYS_NOTIFICATION_TEMPLATE (ID, NOTIFICATION_TITLE, LANGUAGE, APPLYING_ROLE, NOTIFICATION_TYPE, TRANSMIT_CHANNEL, STATUS, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, EMAIL_TITLE)
values ('7ccb0279d9324d2f8caa808ba4dc22a9', 'Employee Reset Password Messengers', '0', '742755ee8a814709a60b967ac8763420', '40', '1', 1, 'admingu', '11-10月-19 04.26.58.709000 下午', 'admin', '15-11月-19 06.11.18.916000 下午', 0, '<p style="text-align: left;">Hello!&nbsp;<span><input value=" Applicant Name " type="button"/></span></p><p style="text-align: left;"><span><br/></span></p><p style="text-align: left;">&nbsp; &nbsp; &nbsp;Your password is reseted! you can login the system with the followed url:</p><p style="text-align: left;"><span><input value=" Registrantion Url" type="button"/></span></p><p style="text-align: left;">user name：<span><input value=" Login_name " type="button"/></span></p><p style="text-align: left;">password：<span><input value=" Login_password " type="button"/></span></p><p style="text-align: right;">Hikvision&nbsp;<span><input value=" Business Area " type="button"/></span></p><p style="text-align: right;"><span><span><input value=" Send Date " type="button"/></span></span></p>', 'Hikvision Personal Information Collection Reset Password Mail');

prompt Done.
