prompt Importing table T_SYS_STATEMENT...
set feedback off
set define off
insert into T_SYS_STATEMENT (ID, STATEMENT_TEMPLATE, LANGUAGE, STATEMENT_TITLE, SUBTITLE, STATUS, APPLYING_ROLE, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, NOTE_TIPS)
values ('961f26cae11a4643e053afa7010a7f25', '9eaefaf1f54d41538e63a7540653ec0b', '2', 'Por favor, lea cuidadosamente', null, 1, 'd35ef0373a6a435f98f6bdb0c70bef05', 'admingu', '30-10月-19 06.25.27.558000 下午', 'admin', '04-11月-19 05.33.49.282000 下午', 0, '<p>Declaro que los hechos contenidos en esta solicitud o cualquier currículum u otra documentación presentada son verdaderos y están completos según lo mejor de mi conocimiento. Entiendo que cualquier información falsa u omisión material me descalificará para ser considerado para un empleo, y si ya está contratado, será una justificación para mi despido.</p><p>Yo declaro que la empresa está autorizada a utilizar los datos mencionados en los documentos e informaciones proporcionadas con fines profesionales.</p><p>Si llego a ser empleado, teniendo en cuenta mi empleo, acepto cumplir con las normas, reglamentos, políticas y procedimientos de la compañía.</p>', null);

insert into T_SYS_STATEMENT (ID, STATEMENT_TEMPLATE, LANGUAGE, STATEMENT_TITLE, SUBTITLE, STATUS, APPLYING_ROLE, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, NOTE_TIPS)
values ('96d428c311154846e053afa7010a68c5', '22b4c17908ec4ab2a313bd8128fc8866', '0', 'Please read carefully', null, 1, 'd35ef0373a6a435f98f6bdb0c70bef05', 'admingu', '08-11月-19 06.22.29.678000 下午', null, null, 0, '<p>I Declare&nbsp; That The Facts Contained In This Application Or Any Resume Or Other Documentation Submitted Are True And Complete To The Best Of My Knowledge.&nbsp; I Understand That Any False Information Or Material Omissions Will Disqualify Me From Consideration For Employment, And If Already Hired, Will Be Justification For My Dismissal From Employment.&nbsp;</p><p>I declare that the company is authorized to use the data mentioned in the documents and information provided for professional purposes.</p><p>If I Become Employed, In Consideration Of My Employment, I Agree To Comply With The Rules, Regulations, Policies And Procedures Of The Company.<br/></p>', null);

insert into T_SYS_STATEMENT (ID, STATEMENT_TEMPLATE, LANGUAGE, STATEMENT_TITLE, SUBTITLE, STATUS, APPLYING_ROLE, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, NOTE_TIPS)
values ('949ead6b33e3447ce053afa7010aebb7', '861ae16b1317424ab61d85b2ea95db39', '0', 'Declaration', 'PLEASE READ CAREFULLY AND INITIAL EACH PARAGRAPH BEFORE SIGNING', 1, 'b8642f9ecea149d4a8aa77353960709a', 'admingu', '11-10月-19 03.45.25.958000 下午', 'admingu', '12-11月-19 12.28.53.443000 下午', 0, '<p>1、I certify that following information is correct &amp; complete to the best of my knowledge and nothing has been concealed. Should I be found to have concealed any material information or given any details, my appointments shall be liable to besummarily terminated without notice or compensation.</p><p><br/></p><p>2、I authorize you to make such investigations and inquiries of my personal, employment,educational, financial, and other related matters as may be necessary for an employment decision.</p><p>3、I hereby release employers, schools, or individuals from all liability when responding to inquiries in connection with my application.</p><p>4、I agree to undergo a medical examination at the clinics appointed by the Company.</p><p>5、Further, I confirm that I have read and understood the above policy and express my consent to the processing of my personal and/or sensitive&nbsp;personal information in this manner and as part of my job application as provided under the laws and its corresponding Rules and Regulations.</p>', 'From time to time,the company may obtain information about you from public records.If you wish to waive your right to receive a copy of any public records,you should check the following box。');

insert into T_SYS_STATEMENT (ID, STATEMENT_TEMPLATE, LANGUAGE, STATEMENT_TITLE, SUBTITLE, STATUS, APPLYING_ROLE, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, NOTE_TIPS)
values ('949ead6b33e4447ce053afa7010aebb7', '619782239da9460bbf8e4e65c0b95fe0', '0', 'Declaration', 'PLEASE READ CAREFULLY AND INITIAL EACH PARAGRAPH BEFORE SIGNING', 1, '3df154d1afa84fa3b786658772c64938', 'admingu', '11-10月-19 03.46.03.465000 下午', 'admin', '23-10月-19 09.45.06.892000 下午', 0, '<p>1、I certify that following information is correct &amp; complete to the best of my knowledge and nothing has been concealed. Should I be found to have concealed any material information or given any details, my appointments shall be liable to besummarily terminated without notice or compensation.</p><p>2、I authorize you to make such investigations and inquiries of my personal, employment,educational, financial, and other related matters as may be necessary for an employment decision.</p><p>3、I hereby release employers, schools, or individuals from all liability when responding to inquiries in connection with my application.</p><p>4、I agree to undergo a medical examination at the clinics appointed by the Company.</p><p>5、Further, I confirm that I have read and understood the above policy and express my consent to the processing of my personal and/or sensitive&nbsp;personal information in this manner and as part of my job application as provided under the laws and its corresponding Rules and Regulations.</p>', 'From time to time,the company may obtain information about you from public records.If you wish to waive your right to receive a copy of any public records,you should check the following box。');

insert into T_SYS_STATEMENT (ID, STATEMENT_TEMPLATE, LANGUAGE, STATEMENT_TITLE, SUBTITLE, STATUS, APPLYING_ROLE, CNAME, CTIME, CHNAME, MTIME, DELETED, CONTENT, NOTE_TIPS)
values ('949ec0bf0e4c4622e053afa7010aad9f', '59482c9f6318455e8e7ee0210d863e2a', '1', 'Por favor, leia atentamente', null, 1, 'd35ef0373a6a435f98f6bdb0c70bef05', 'admingu', '11-10月-19 03.49.08.074000 下午', 'admin', '04-11月-19 05.32.19.214000 下午', 0, '<p>Eu declaro que os fatos contidos nesta aplicação ou qualquer currículo ou outra documentação enviada são verdadeiros e completos para o melhor do meu conhecimento. Eu entendo que qualquer informação falsa ou material que me desqualificará da consideração para o emprego, e se já contratado, será justificação para minha destituição do emprego.</p><p>Eu declaro que a empresa está autorizada a utilizar os dados mencionados nos documentos e informações providenciadas para fins profissionais.&nbsp;</p><p>Se eu me tornar empregado, em consideração ao meu emprego, eu concordo em cumprir as regras, regulamentos, políticas e procedimentos da empresa.</p>', null);

prompt Done.
